<?php

/**
 * Implements hook_ctools_plugin_directory
 *
 * Tell Ctools where the plugin files are that will help expose our
 * exportable stuff to the built in Ctools Export UI tools.
 */
function eg_exportable_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Edit form for our record/object.
 */
function exportable_stuff_form(&$form, $form_state) {

  $form['hint'] = array(
    '#type' => 'markup',
    '#markup' => t('<p>Here you might code a form so the object can be edited, but it\'s not provided in this example.</p>'),
  );
}

/**
 * Validate handler for above.
 */
function exportable_stuff_form_validate(&$form, $form_state) {
}

/**
 * Submit handler for above.
 */
function exportable_stuff_form_submit(&$form, $form_state) {
}